---
abstract: unknown
author:
  - 'Nils Diewald'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-MagicSignatures-Key
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Digest::SHA: 0
  Exporter: 0
  MIME::Base64: 0
  Math::BigInt: 0
  Math::Prime::Util: 0.10
  Math::Random::Secure: 0.05
  Test::More: 0
  perl: 5.010001
resources:
  license: http://www.opensource.org/licenses/artistic-license-2.0
  repository: https://github.com/Akron/Crypt-MagicSignatures-Key
version: 0.02
